//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopulationCensu
    {
        public int ApplicationId { get; set; }
        public int MemberId { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Suffix { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
    }
}
